name: Sync with Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # Täglich um 2 Uhr
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dein Fork-Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add upstream and merge
      run: |
        git remote add upstream https://github.com/NMminer1024/NMController_web.git
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories --no-edit || true
        git push origin main

    - name: Trigger Docker Build Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: force-docker-build
